name: 'multigitminder'
description: 'Create data point via Beeminder API'
author: 'Hayden MacDonald <hmd@needleinthehay.ca>'
inputs:
  auth_token: 
    description: 'Unique authorization token for Beeminder API'
    required: true
  goal:
    description: 'Name of the user's goal.'
    required: true
  comment:
    description: 'Optional comment about the data point.'
    required: true
    default: 'logged to API via multigitminder'
outputs:
  time:
    description: 'The time the data point request was made to the API'
  data:
    description: 'The data object returned by the Beeminder API'
runs:
  using: 'node12'
  main: 'dist/index.js'