name: 'multigitminder'
description: 'Create data points via Beeminder API'
author: 'Hayden MacDonald <hmd@needleinthehay.ca>'
branding:
  icon: "zap"
  color: "yellow"
inputs:
  USERNAME:
    description: 'Beeminder username.'
    required: true
  AUTH_TOKEN: 
    description: 'Unique authorization token for Beeminder API.'
    required: true
  GOAL:
    description: 'Name of the goal.'
    required: true
  VALUE:
    description: 'Value of data point input.'
    required: false
    default: 1
  COMMENT:
    description: 'Optional comment about the data point.'
    required: false
runs:
  using: 'docker'
  image: 'Dockerfile'