name: 'Hello World'
description: 'Greet someone and record the time'
author: 'Hayden MacDonald <hmd@needleinthehay.ca>'
inputs:
  who-to-greet:  # id of input
    description: 'Who to greet'
    required: true
    default: 'World'
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'node12'
  main: 'index.js'