name: 'multigitminder'
description: 'Create data points via Beeminder API'
author: 'Hayden MacDonald <hmd@needleinthehay.ca>'
branding:
  icon: "zap"
  color: "yellow"
inputs:
  USERNAME:
    description: 'Beeminder username.'
    required: true
  AUTH_TOKEN:
    description: 'Unique authorization token for Beeminder API.'
    required: true
  TIME_ZONE:
    description: 'User timezone in IANA time zone format'
    required: false
  GOAL:
    description: 'Name of the goal.'
    required: true
  VALUE:
    description: 'Value of data point input.'
    required: true
    default: '1'
  COMMENT:
    description: 'Optional comment about the data point.'
    required: false
  TARGET_LANGS:
    description: 'Optional input for target language related to goal.'
    required: false
  REPO_LANGS:
    description: 'Optional JSON data of repo languages from fabasoad/linguist-action to accomodate language-based goals.'
    required: false
runs:
  using: 'docker'
  image: 'Dockerfile'