name: multigitminder
on:
  push:
    branches: [ main, lang ]
  issues:
    types: [ closed ]

jobs:
  multigitminder:
    runs-on: ubuntu-latest
    name: multigitminder
    steps:
      # Checkout 
      # TODO Integrate github/linguist action to analyze repo languages
      #  labels: enhancement
      - name: Checkout
        uses: actions/checkout@v2
      - name: "TODO to Issue"
        uses: "alstr/todo-to-issue-action@v2.4.1"
        id: "todo"
        with:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
      # linguist
      - name: Linguist Action
        uses: fabasoad/linguist-action@v1.0.2
        id: linguist
        with:
          path: './'
          percentage: true
      # multigitminder
      - name: multigitminder
        uses: HaydenMacDonald/multigitminder@lang
        id: multigitminder
        with:
          USERNAME: ${{ secrets.BEEMINDER_USERNAME }}
          AUTH_TOKEN: ${{ secrets.BEEMINDER_AUTH_TOKEN }}
          GOAL: multigitminder
          VALUE: 1
          TARGET_LANGS: [ Python, dockerfile ]
          REPO_LANGS: ${{ steps.linguist.outputs.data }}
