name: multigitminder
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main , pyminder]
  pull_request:
    branches: [ main ]

jobs:
  multigitminder:
    runs-on: ubuntu-latest
    name: multigitminder
    steps:
      # Use current directory
      - name: Checkout
        uses: actions/checkout@v2
      - name: multigitminder
        uses: HaydenMacDonald/multigitminder@main
        id: multigitminder
        with:
          USER_NAME: ${{ secrets.BEEMINDER_USER_NAME }}
          AUTH_TOKEN: ${{ secrets.BEEMINDER_AUTH_TOKEN }}
          GOAL: multigitminder
      # - run: echo ${{ steps.multigitminder.outputs.time }}
      - name: Time Output
        run: echo ${{ steps.multigitminder.outputs.TIME }}
      - name: Data Output
        run: echo ${{ steps.multigitminder.outputs.DATA }}
