name: multigitminder
on:
  push:
    branches: [ main, hash ]
  issues:
    types: [ closed ]

jobs:
  multigitminder:
    runs-on: ubuntu-latest
    name: multigitminder
    steps:
      # Checkout 
      # TODO Integrate github/linguist action to analyze repo languages
      #  labels: enhancement
      - name: Checkout
        uses: actions/checkout@v2
      - name: "TODO to Issue"
        uses: "alstr/todo-to-issue-action@v2.4.1"
        id: "todo"
        with:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
      # multigitminder
      - name: multigitminder
        uses: HaydenMacDonald/multigitminder@hash
        id: multigitminder
        with:
          USERNAME: ${{ secrets.BEEMINDER_USERNAME }}
          AUTH_TOKEN: ${{ secrets.BEEMINDER_AUTH_TOKEN }}
          GOAL: multigitminder
          VALUE: 1
