name: multigitminder
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  multigitminder:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      # Use current directory
      - uses: ./
        with:
          auth_token: ${{ secrets.BEEMINDER_AUTH_TOKEN }}
          goal: multigitminder
        id: multigitminder
      # - run: echo ${{ steps.multigitminder.outputs.time }}
      - run: echo ${{ steps.multigitminder.outputs.data }}
