name: multigitminder
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main , pyminder]
  pull_request:
    branches: [ main ]

jobs:
  multigitminder:
    runs-on: ubuntu-latest
    steps:
      # Use current directory
      - uses: actions/checkout@v2
      - uses: ./
        id: multigitminder
        with:
          USER_NAME: ${{ secrets.BEEMINDER_USER_NAME }}
          AUTH_TOKEN: ${{ secrets.BEEMINDER_AUTH_TOKEN }}
          GOAL: multigitminder
      # - run: echo ${{ steps.multigitminder.outputs.time }}
      - run: echo ${{ steps.multigitminder.outputs.data }}
